---
title: "Training Analysis For Object Recognition"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(ggplot2)

source("analyzeTraining.R")

trainResults <- loadResults("./results", "newarchtrial", "trainingData.csv")
```

## Results summary

```{r, echo=FALSE}
trainResults %>%
  group_by(id, folder, minibatch, alpha, dropout, l2) %>%
  summarise(testLoss=min(test_loss),
            testAcc=max(test_accuracy),
            trainLoss=min(train_loss),
            trainAcc=max(train_accuracy)
            ) %>%
  arrange(desc(testAcc), trainAcc)
``` 

```{r, echo=FALSE, fig.width=10, fig.height = 10, fig.width=12, fig.height = 6}
trainResults %>%
  select(id, iteration, test_accuracy, train_accuracy) %>%
  filter(iteration > 3000) %>%
  gather(metric, value, -iteration, -id) %>%
  ggplot(aes(x=iteration, y=value, color=metric)) +
    geom_smooth()
```

```{r, echo=FALSE, fig.width=10, fig.height =6}
trainResults %>% 
  select(id, iteration, test_loss, train_loss) %>%
  filter(iteration > 3000) %>%
  gather(metric, value, -iteration, -id) %>%
  ggplot(aes(x=iteration, y=value, color=metric)) +
    geom_smooth()
```




